#!/usr/bin/env bash

set -eu

cd /lambda/

# Create zip
zip -9R /deploy/function.zip *

# Upload to aws
aws lambda update-function-code --function-name ${LAMBDA_FUNCTION_NAME} --zip-file fileb:///deploy/function.zip
