#!/usr/bin/env bash

set -eu

cd /lambda/

# Create zip
zip -9r /deploy/function.zip *

# Upload to aws
if [ "false" == "$NO_UPDATE_FUNCTION" ] || [ ! "$NO_UPDATE_FUNCTION" ];then
	aws lambda update-function-code --function-name ${LAMBDA_FUNCTION_NAME_YES_UPDATE_FUNCTION} --zip-file fileb:///deploy/function.zip
fi
